GET http://localhost:3000/plannedRoute

###

POST http://localhost:3000/plannedRoute
Content-Type: application/json

{
  "tip": "test",
  "strada": "test",
  "data": "test",
  "luni": false,
  "marti": false,
  "miercuri": false,
  "joi": false,
  "vineri": false,
  "sambata": false,
  "duminica": false
}

###

DELETE http://localhost:3000/plannedRoute/67cc48d2d639acc8bb17aa9f


####